### ISSUE TITLE
Calibration

### ISSUE THREAD

**Issue by mattcelt** [BernsteinA/GfxTablet-OSXDaemon#1]
Heya - first, a tremendous CHEERS! to you for this.  It works like a charm, even with the hover.

The only trouble I'm having is with calibration.  I have a 13" Macbook Pro with a retina display, and a Samsung Galaxy Note 8...  the GfxTablet app on the Note seems to be expecting a larger workspace - the Mac's screen width only takes up about half the tablet's real-estate, and I can't _quite_ reach the left edge of the Mac's screen with the Pen's input.

I'm guessing your setup was with devices with different resolutions, and I'm not accomplished enough with python to know how to change the parameters in your code... how do I tell the program what the proper parameters are?

Thanks so much again for your work on this - I'd be lost without it!

**Comment by BernsteinA** [comment]
Wow, I had no idea anybody used this!
I probably wrote it before I got a retina Mac; I'm assuming that's what's causing the resolutions not to line up.
Will see what I can do

**Comment by BernsteinA** [comment]
@mattcelt as a quick fix, search in the file and remove the instances of "*2.0

**Comment by mattcelt** [comment]
I'll give that a shot.

I also found this:

import gtk, pygtk

window = gtk.Window()
screen = window.get_screen()
print "width = " + str(screen.get_width()) + ", height = " + str(screen.get_height())


Here:
https://stackoverflow.com/questions/3375740/get-screen-size-in-python

I don't know if that helps, but hopefully so.  :-)

I'll let you know how removing the *2.0 bit works.

**Comment by mattcelt** [comment]
Removing the *2.0 seems to have worked very well.  I'm getting a 1:1 mapping of the screens now.

If I wanted to reduce the size a bit, could I use a smaller multiplier (*1.3 or *1.5)?  And would it be possible to add an offset?  (I'm left-handed, so I'd like to move the touch area to the right - or perhaps a 180-degree rotation would work?  Where would I input that?)

Thanks again for doing this!

**Comment by BernsteinA** [comment]
For an offset, add or subtract in mousemove and mouseclick, or modify the
rect variable after getdisplaybounds.
I can't teach programming by correspondence here. Suggest you play around
with the code and see what happens!
